---
#


- set_fact:
    maven_profile_file: "$HOME/.profile"
  when: ansible_os_family == "Debian"

- set_fact:
    maven_profile_file: "{{ ansible_env.HOME }}/.bash_profile"
  when: ansible_os_family == "RedHat"

- name: set maven variables
  lineinfile:
   dest: "{{ maven_profile_file }}"
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
   insertbefore: "export PATH"
  with_items:
   -
     regexp: "^M2_HOME="
     line: "M2_HOME={{ maven_home }}"
   -
     regexp: ^PATH=\$M2_HOME/bin
     line: PATH=\$M2_HOME/bin:$PATH
   -
     regexp: "^export M2_HOME"
     line: export M2_HOME
