---
#
- name: prepare maven directory
  file:
    path: "{{ maven_base }}"
    state: directory



- name: unarchive file
  unarchive:
    src: "http://www.apache.org/dist/maven/maven-{{ maven_version }}/{{ maven_release }}/binaries/apache-maven-{{ maven_release }}-bin.tar.gz"
    dest: "{{ maven_base }}"
    copy: no
