---
#
- name: prepare maven directory
  file:
    path: "{{ maven_base }}"
    state: directory



- name: unarchive file
  unarchive:
    src: "http://www.apache.org/dist/maven/maven-{{ maven_version }}/{{ maven_release }}/binaries/apache-maven-{{ maven_release }}-bin.tar.gz"
    dest: "{{ maven_base }}"
    copy: no

- set_fact:
    profile_file: "$HOME/.profile"
  when: ansible_os_family == "Debian"

- set_fact:
    profile_file: "{{ ansible_env.HOME }}/.bash_profile"
  when: ansible_os_family == "RedHat"

- name: set maven variables
  lineinfile:
   dest: "{{ profile_file }}"
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
   insertbefore: "export PATH"
  with_items:
   -
     regexp: "^M2_HOME="
     line: "M2_HOME={{ maven_home }}"
   -
     regexp: ^PATH=\$M2_HOME/bin:
     line: PATH=\$M2_HOME/bin:$PATH
   -
     regexp: ^export M2_HOME
     line: export M2_HOME
