---
#
- name: prepare maven directory
  file:
    path: "{{ maven_base }}"
    state: directory



- name: unarchive file
  unarchive:
    src: "http://www.apache.org/dist/maven/maven-{{ maven_version }}/{{ maven_release }}/binaries/apache-maven-{{ maven_release }}-bin.tar.gz"
    dest: "{{ maven_base }}"
    copy: no

- set_fact:
    profile_file: "$HOME/.profile"
  when: ansible_os_family == "Debian"

- set_fact:
    profile_file: "{{ ansible_env.HOME }}/.bash_profile"
  when: ansible_os_family == "RedHat"
